### ISSUE TITLE
Idea: Add pi-manage script

### ISSUE THREAD

**Issue by fredreichbier** [NetKnights-GmbH/centos7#2]
Even though privacyIDEA lives in a virtualenv, the RPM could add a global pi-manage script like that:
/usr/bin/pi-manage
```
#!/bin/sh
/opt/privacyidea/bin/pi-manage "$@"
```

**Comment by cornelinux** [comment]
but we would have to source the virtualenv!?

**Comment by plettich** [comment]
Actually when installing in a virtualenv, the path to the correct python binary is set in ``pi-manage``, so this should not be a problem.

**Comment by cornelinux** [comment]
We actually did this in the ubuntu packages to create links from

/opt/privacyidea/bin/pi-manage -> /usr/bin/

THis way you do not need to define the complete path.
I like this, we will do it here, too.
